name: Bash Script
on:
  push:

jobs:
  bash-script:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Use Go 1.13
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.13.x

      - uses: jaxxstorm/action-install-gh-release@v1.12.0 
        with:
          repo: tmedwards/tweego
          chmod: 0775

      - name: Run Bash script
        run: bash ./build.sh
        env:
          PGDATABASE: ${{ vars.PGDATABASE }}
          PGPORT: ${{ vars.PGPORT }}
          PGUSER: ${{ vars.PGUSER }}
          PGHOST: ${{ vars.PGHOST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
      
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: event_logs_backup

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: events-old_*.json

      - name: Commit Compiled Bridges
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
