name: Bash Script
on:
  push:

jobs:
  bash-script:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Use Go 1.13
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.13.x

      - uses: jaxxstorm/action-install-gh-release@v1.12.0 
        with:
          repo: tmedwards/tweego
          chmod: 0775

      - name: Run Bash script
        run: bash ./build.sh
        env:
          PGDATABASE: ${{ vars.PGDATABASE }}
          PGPORT: ${{ vars.PGPORT }}
          PGUSER: ${{ vars.PGUSER }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}


      - name: Commit Compiled Bridges
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
